apiVersion: v1
kind: Pod
metadata:
  name: test-nginx
  labels:
    name: test-nginx
spec:
  hostIPC: true
  hostPid: true
  containers:
  - name: test-nginx
    image: nginx
    imagePullPolicy: Always
    stdin: true
    tty: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
