apiVersion: v1
kind: Pod
metadata:
  name: app-1
spec: 
  nodeSelector:
    kubernetes.io/hostname: 172.31.2.11
  containers:
    - name: nginx
      image: nginx:1.16.0
      imagePullPolicy: Always
      tty: true
      stdin: true
      resources:
        limits:
          memory: "256Mi"
          cpu: "200m"
        requests:
          memory: "128Mi"
          cpu: "50m"
    - name: mysql
      image: mysql:5.7.26
      imagePullPolicy: Always
      tty: true
      stdin: true
      resources:
        limits:
          memory: "256Mi"
          cpu: "200M"
        requests:
          memory: "128Mi"
          cpu: "100m"
